### PR TITLE
Updated examples

### PR DESCRIPTION
**Pull request by noemide**
Added single files instead of bundle

### CODE REVIEW

**Comment by noemide** [comment]
Slicing on ValueSets is still discussed in the community https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Slicing.20and.20value.20sets/near/178283938 . I'll try to find a solution that works with the current validator...

**Comment by alexanderkiel** [comment]
I would slept that PR. Single files here and slicing relevant new examples in the other PR.

**Review by alexanderkiel — CHANGES_REQUESTED** [review]
The build is still failing.

**Comment by noemide** [comment]
> 
> 
> The build is still failing.

Using the fixed profiles, it works now.

**Review by alexanderkiel — APPROVED** [review]

**Pull request merged**
